apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prisma.database.secretName }}
  labels:
    app: prisma
type: Opaque
stringData:
  DATABASE_URL: "postgresql://{{ .Values.prisma.database.dbUser }}:{{ .Values.postgresql.auth.password }}@{{ .Values.prisma.database.dbHost }}:{{ .Values.prisma.database.dbPort }}/{{ .Values.prisma.database.dbName }}"

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwt.secret.name }}
  labels:
    app: saju
type: Opaque
stringData
  key: {{ .Values.jwt.secret.key }}

